version: "3.8"

services:
  mysql:
    image: mysql:latest
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_DB_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DB
    ports:
      - 3306:3307
  app:
    depends_on:
      - mysql
    build: ./
    env_file: ./.env
    ports:
      - 8091:8091


