server:
  port: 8091

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_DB_PORT}/${MYSQL_DB}
    username: ${MYSQL_DB_USER}
    password: ${MYSQL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
